"""catalog and reservations

Revision ID: b4ca05805ca7
Revises: 
Create Date: 2026-10-09 23:51:48.993698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from wandersync_common.migrations import grant_catalog_access, revoke_catalog_access


# revision identifiers, used by Alembic.
revision: str = 'b4ca05805ca7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_offers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('operated_by', sa.String(length=100), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stops', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('price_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_original', sa.String(length=3), nullable=False),
    sa.Column('seats_total', sa.Integer(), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cabin_class IN ('ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST')", name=op.f('ck_flight_offers_cabin_class_valid')),
    sa.CheckConstraint('arrival_at > departure_at', name=op.f('ck_flight_offers_arrival_after_departure')),
    sa.CheckConstraint('price > 0 AND price_original > 0', name=op.f('ck_flight_offers_price_positive')),
    sa.CheckConstraint('seats_available >= 0 AND seats_available <= seats_total', name=op.f('ck_flight_offers_seats_available_range')),
    sa.CheckConstraint('seats_total > 0', name=op.f('ck_flight_offers_seats_total_positive')),
    sa.CheckConstraint('stops >= 0', name=op.f('ck_flight_offers_stops_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_offers')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_flight_offers_source_external_id')),
    schema='flights'
    )
    op.create_index('ix_flight_offers_search', 'flight_offers', ['origin', 'destination', 'departure_at'], unique=False, schema='flights')
    op.create_table('reservations',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('saga_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'CANCELLED' OR (offer_id IS NOT NULL AND quantity > 0)", name=op.f('ck_reservations_offer_required')),
    sa.CheckConstraint("status IN ('RESERVED', 'CONFIRMED', 'CANCELLED')", name=op.f('ck_reservations_status_valid')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_reservations_quantity_non_negative')),
    sa.ForeignKeyConstraint(['offer_id'], ['flights.flight_offers.id'], name=op.f('fk_reservations_offer_id_flight_offers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('saga_id', name=op.f('uq_reservations_saga_id')),
    schema='flights'
    )
    # ### end Alembic commands ###

    # Matriz de privilegios (modelo-datos.md): `ingest` no puede actualizar el inventario.
    grant_catalog_access(
        "flights",
        "flight_offers",
        ingest_update_columns=['price', 'currency', 'price_original', 'currency_original', 'operated_by', 'flight_number', 'stops', 'scraped_at', 'updated_at'],
    )


def downgrade() -> None:
    revoke_catalog_access("flights", "flight_offers")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations', schema='flights')
    op.drop_index('ix_flight_offers_search', table_name='flight_offers', schema='flights')
    op.drop_table('flight_offers', schema='flights')
    # ### end Alembic commands ###
