"""catalog and reservations

Revision ID: 9a58f8139fe8
Revises: 
Create Date: 2026-10-09 23:51:58.194721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from wandersync_common.migrations import grant_catalog_access, revoke_catalog_access


# revision identifiers, used by Alembic.
revision: str = '9a58f8139fe8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_offers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('hotel_code', sa.String(length=20), nullable=False),
    sa.Column('hotel_name', sa.String(length=150), nullable=False),
    sa.Column('city_code', sa.String(length=3), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('stars', sa.SmallInteger(), nullable=True),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('room_code', sa.String(length=30), nullable=False),
    sa.Column('room_name', sa.String(length=150), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('board_code', sa.String(length=10), nullable=False),
    sa.Column('board_name', sa.String(length=50), nullable=False),
    sa.Column('max_guests', sa.SmallInteger(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('nights', sa.SmallInteger(), sa.Computed('check_out - check_in', persisted=True), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('price_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_original', sa.String(length=3), nullable=False),
    sa.Column('rooms_total', sa.Integer(), nullable=False),
    sa.Column('rooms_available', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("room_type IN ('SINGLE', 'DOUBLE', 'TWIN', 'SUITE', 'FAMILY', 'OTHER')", name=op.f('ck_room_offers_room_type_valid')),
    sa.CheckConstraint('check_out > check_in', name=op.f('ck_room_offers_checkout_after_checkin')),
    sa.CheckConstraint('max_guests > 0', name=op.f('ck_room_offers_max_guests_positive')),
    sa.CheckConstraint('price_per_night > 0 AND price_total > 0 AND price_original > 0', name=op.f('ck_room_offers_price_positive')),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 0 AND 10', name=op.f('ck_room_offers_rating_range')),
    sa.CheckConstraint('rooms_available >= 0 AND rooms_available <= rooms_total', name=op.f('ck_room_offers_rooms_available_range')),
    sa.CheckConstraint('rooms_total > 0', name=op.f('ck_room_offers_rooms_total_positive')),
    sa.CheckConstraint('stars IS NULL OR stars BETWEEN 1 AND 5', name=op.f('ck_room_offers_stars_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_offers')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_room_offers_source_external_id')),
    schema='hotels'
    )
    op.create_index('ix_room_offers_hotel_code', 'room_offers', ['hotel_code'], unique=False, schema='hotels')
    op.create_index('ix_room_offers_search', 'room_offers', ['city_code', 'check_in', 'check_out'], unique=False, schema='hotels')
    op.create_table('reservations',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('saga_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'CANCELLED' OR (offer_id IS NOT NULL AND quantity > 0)", name=op.f('ck_reservations_offer_required')),
    sa.CheckConstraint("status IN ('RESERVED', 'CONFIRMED', 'CANCELLED')", name=op.f('ck_reservations_status_valid')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_reservations_quantity_non_negative')),
    sa.ForeignKeyConstraint(['offer_id'], ['hotels.room_offers.id'], name=op.f('fk_reservations_offer_id_room_offers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('saga_id', name=op.f('uq_reservations_saga_id')),
    schema='hotels'
    )
    # ### end Alembic commands ###

    # Matriz de privilegios (modelo-datos.md): `ingest` no puede actualizar el inventario.
    grant_catalog_access(
        "hotels",
        "room_offers",
        ingest_update_columns=['hotel_name', 'zone_name', 'address', 'latitude', 'longitude', 'stars', 'category_name', 'rating', 'room_name', 'room_type', 'board_name', 'max_guests', 'price_per_night', 'price_total', 'currency', 'price_original', 'currency_original', 'scraped_at', 'updated_at'],
    )


def downgrade() -> None:
    revoke_catalog_access("hotels", "room_offers")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations', schema='hotels')
    op.drop_index('ix_room_offers_search', table_name='room_offers', schema='hotels')
    op.drop_index('ix_room_offers_hotel_code', table_name='room_offers', schema='hotels')
    op.drop_table('room_offers', schema='hotels')
    # ### end Alembic commands ###
