"""catalog and reservations

Revision ID: e1d9932fc2bf
Revises: 
Create Date: 2026-10-09 23:52:05.950377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from wandersync_common.migrations import grant_catalog_access, revoke_catalog_access


# revision identifiers, used by Alembic.
revision: str = 'e1d9932fc2bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_offers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=10), nullable=False),
    sa.Column('seats', sa.SmallInteger(), nullable=False),
    sa.Column('city_code', sa.String(length=3), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('dropoff_date', sa.Date(), nullable=False),
    sa.Column('days', sa.SmallInteger(), sa.Computed('dropoff_date - pickup_date', persisted=True), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('price_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_original', sa.String(length=3), nullable=False),
    sa.Column('units_total', sa.Integer(), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('ECONOMY', 'COMPACT', 'SUV', 'VAN', 'LUXURY')", name=op.f('ck_car_offers_category_valid')),
    sa.CheckConstraint("transmission IN ('MANUAL', 'AUTOMATIC')", name=op.f('ck_car_offers_transmission_valid')),
    sa.CheckConstraint('dropoff_date > pickup_date', name=op.f('ck_car_offers_dropoff_after_pickup')),
    sa.CheckConstraint('price_per_day > 0 AND price_total > 0 AND price_original > 0', name=op.f('ck_car_offers_price_positive')),
    sa.CheckConstraint('seats > 0', name=op.f('ck_car_offers_seats_positive')),
    sa.CheckConstraint('units_available >= 0 AND units_available <= units_total', name=op.f('ck_car_offers_units_available_range')),
    sa.CheckConstraint('units_total > 0', name=op.f('ck_car_offers_units_total_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car_offers')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_car_offers_source_external_id')),
    schema='cars'
    )
    op.create_index('ix_car_offers_search', 'car_offers', ['city_code', 'pickup_date', 'dropoff_date'], unique=False, schema='cars')
    op.create_table('reservations',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('saga_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'CANCELLED' OR (offer_id IS NOT NULL AND quantity > 0)", name=op.f('ck_reservations_offer_required')),
    sa.CheckConstraint("status IN ('RESERVED', 'CONFIRMED', 'CANCELLED')", name=op.f('ck_reservations_status_valid')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_reservations_quantity_non_negative')),
    sa.ForeignKeyConstraint(['offer_id'], ['cars.car_offers.id'], name=op.f('fk_reservations_offer_id_car_offers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('saga_id', name=op.f('uq_reservations_saga_id')),
    schema='cars'
    )
    # ### end Alembic commands ###

    # Matriz de privilegios (modelo-datos.md): `ingest` no puede actualizar el inventario.
    grant_catalog_access(
        "cars",
        "car_offers",
        ingest_update_columns=['company', 'model', 'category', 'transmission', 'seats', 'price_per_day', 'price_total', 'currency', 'price_original', 'currency_original', 'scraped_at', 'updated_at'],
    )


def downgrade() -> None:
    revoke_catalog_access("cars", "car_offers")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations', schema='cars')
    op.drop_index('ix_car_offers_search', table_name='car_offers', schema='cars')
    op.drop_table('car_offers', schema='cars')
    # ### end Alembic commands ###
